server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-p8f9pfsv3q-stack-awsebrdsdatabase-bcbtm1zuknzi.cxaq4gs2wvsw.ap-northeast-2.rds.amazonaws.com:3306/todo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: todo
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
